server:
  port: 10010
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api #添加路由前缀
  retryable: true # 重试
  routes:
    item-service: /item/** #(商品微服务)网关接收到 /item/** 转发到application name 为 item-service服务去
    search-service: /search/** #搜索微服务
    user-service: /user/** #用户模块
    auth-service: /auth/** #授权
    cart-service: /cart/** #购物车
    order-service: /order/** #支付
  # http://api.leyou.com/api/item/category/list?pid=0
  add-host-header: true #携带请求本身的host头信息
  sensitive-headers:  #敏感头过滤将失效
  ignored-services:
    - upload-service
ribbon:
  eureka:
    enabled: true #开启eureka的ribbon功能
    ConnectionTimeout: 250 # 连接超时时间(ms)
    ReadTimeout: 2000 # 通信超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 #熔断超时时长 10000ms(10s)

ly:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub #公钥地址
    cookieName: LY_TOKEN #cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item