server:
  port: 8087
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?serverTimezone=UTC
    username: root
    password: tayujiu99
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&hei% # 登录校验的密钥
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
    priKeyPath: D:/rsa/rsa.pri # 私钥地址
    expire: 30 # token的过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 1800